autoload:
  infra:
    name:           infra
    path:           %KALTURA_INFRA_DIR%
#    prefix:         1
    recursive:      on   
    
  server_infra:
    name:           server_infra
    path:           %KALTURA_SERVER_INFRA_DIR%
#    prefix:         1
    recursive:      on   
    
  plugins:
    name:           plugins
    path:           %KALTURA_PLUGINS_DIR%
    recursive:      on   
    
    
  propel:
    name:           propel
    path:           %KALTURA_VENDOR_DIR%/propel
#    prefix:         1
    recursive:      on   
    
    
  zend:
    name:           zend
    path:           %KALTURA_VENDOR_DIR%/ZendFramework/library
#    prefix:         1
    recursive:      on   
